- type: department
  id: Expeditionary
  name: department-Expeditionary
  description: department-Expeditioneering-description
  color: "#846DCF"
  roles:
  - TP14Expeditioneer
  - TP14BasinTech
  - TP14Pilot
