- type: job
  id: TP14Pilot
  name: job-name-pilot
  description: job-description-pilot
  playTimeTracker: TP14PilotTracker
  icon: "JobIconShaftMiner"
  startingGear: TP14PilotGear
  supervisors: job-supervisors-qm
  access:
  - Salvage
  - Maintenance
  - External
  requirements:
  - !type:DepartmentTimeRequirement
    department: Expeditionary
    time: 3600 # 1 hr
  special:
  - !type:AddComponentSpecial
    components:
    - type: ExpedPilot # Allows them to use their mech

- type: startingGear
  id: TP14PilotGear
  equipment:
    id: TP14PilotPDA
    ears: ClothingHeadsetMining

- type: chameleonOutfit
  id: PilotGearChameleonOutfit
  job: TP14Pilot
  equipment:
    head: ClothingHeadHatHardhatArmored
    mask: ClothingMaskGasExplorer
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterWinterMiner
    gloves: ClothingHandsGlovesFingerless
    shoes: ClothingShoesColorBlack
